import React, { useState } from 'react';
import { 
  Droplet, 
  ShieldCheck, 
  Rocket, 
  Terminal, 
  Copy, 
  ExternalLink, 
  CheckCircle2, 
  Coins, 
  FileCode,
  Check
} from 'lucide-react';

export default function SuiForge({ onNavigate, wallet, onShowToast }) {
  const [tokenName, setTokenName] = useState('Sui Pulse');
  const [symbol, setSymbol] = useState('SPULSE');
  const [decimals, setDecimals] = useState(9);
  const [supply, setSupply] = useState('1000000000');
  const [logoUrl, setLogoUrl] = useState('https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=100&q=80');
  const [description, setDescription] = useState('High-performance Sui Move community token created via 20LAB.');
  const [network, setNetwork] = useState('testnet'); // 'testnet' or 'mainnet'

  const [fixedSupply, setFixedSupply] = useState(true);
  const [deploying, setDeploying] = useState(false);
  const [deployedSui, setDeployedSui] = useState(null);

  const cleanModule = (symbol || 'MYTOKEN').replace(/[^a-zA-Z0-9]/g, '_').toLowerCase();
  const cleanStruct = (symbol || 'MYTOKEN').replace(/[^a-zA-Z0-9]/g, '_').toUpperCase();

  const generatedMoveCode = `// SPDX-License-Identifier: MIT
// Generated by 20LAB.app Sui Token Engine
module ${cleanModule}::${cleanModule} {
    use std::option;
    use sui::coin::{Self, Coin, TreasuryCap};
    use sui::transfer;
    use sui::tx_context::{Self, TxContext};
    use sui::url;

    /// One-Time-Witness (OTW) for the token currency
    public struct ${cleanStruct} has drop {}

    fun init(witness: ${cleanStruct}, ctx: &mut TxContext) {
        let (treasury_cap, metadata) = coin::create_currency(
            witness,
            ${decimals}, // Decimals
            b"${symbol}", // Symbol
            b"${tokenName}", // Name
            b"${description}", // Description
            option::some(url::new_unsafe_from_bytes(b"${logoUrl}")),
            ctx
        );

        // Lock metadata immutability
        transfer::public_freeze_object(metadata);

        // Mint initial supply
        let initial_coin = coin::mint(&mut treasury_cap, ${supply} * 1000000000, ctx);
        transfer::public_transfer(initial_coin, tx_context::sender(ctx));

        ${fixedSupply ? `// Fixed supply guarantee: Transfer treasury cap to 0x0
        transfer::public_freeze_object(treasury_cap);` : `// Retain treasury capability for minting
        transfer::public_transfer(treasury_cap, tx_context::sender(ctx));`}
    }

    ${!fixedSupply ? `public entry fun mint(
        treasury_cap: &mut TreasuryCap<${cleanStruct}>,
        amount: u64,
        recipient: address,
        ctx: &mut TxContext
    ) {
        coin::mint_and_transfer(treasury_cap, amount, recipient, ctx);
    }` : ''}
}`;

  const handleDeploySui = () => {
    setDeploying(true);
    setTimeout(() => {
      const mockPackageId = '0x9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b';
      const result = {
        name: tokenName,
        symbol,
        decimals,
        supply,
        network,
        packageId: mockPackageId,
        txDigest: '8b7x...SuiDigest',
        fixedSupply
      };
      setDeployedSui(result);
      setDeploying(false);
      onShowToast({
        type: 'success',
        title: 'Sui Move Token Deployed!',
        message: `${tokenName} (${symbol}) published on Sui ${network}!`
      });
    }, 1800);
  };

  const copyToClipboard = (text, label) => {
    navigator.clipboard.writeText(text);
    onShowToast({
      type: 'info',
      title: 'Copied',
      message: `${label} copied to clipboard!`
    });
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8 font-serif">
      
      {/* Breadcrumbs */}
      <div className="font-serif text-sm text-foreground/50 flex flex-wrap gap-2 items-center">
        <button onClick={() => onNavigate?.('/')} className="text-primary-alt hover:underline cursor-pointer">
          Home
        </button>
        <span>/</span>
        <button onClick={() => onNavigate?.('/generate/')} className="text-primary-alt hover:underline cursor-pointer">
          Generate
        </button>
        <span>/</span>
        <div className="text-white">Sui Token Creator</div>
      </div>

      {/* Banner */}
      <div className="p-8 rounded-3xl bg-gradient-to-br from-[#0b2034] via-[#1a3249] to-[#0c0c1c] border border-[#07e3f8]/30 shadow-2xl relative overflow-hidden">
        <div className="relative z-10 max-w-3xl">
          <div className="inline-flex items-center space-x-2 px-3 py-1 rounded-full bg-[#07e3f8]/10 border border-[#07e3f8]/30 text-[#07e3f8] text-xs font-semibold font-serif mb-3">
            <Droplet className="w-3.5 h-3.5 text-[#07e3f8]" />
            <span>Sui Move Token Engine (Coin&lt;T&gt; Standard)</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-bold font-serif text-white">
            Sui Token Creator
          </h1>
          <p className="mt-2 font-serif text-slate-300 text-sm sm:text-base leading-relaxed">
            Generate, compile, and deploy official Sui Move Coin standards with One-Time-Witness (OTW), Cetus DEX compatibility, and immutability controls.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left 2 Cols: Form & Move Code */}
        <div className="lg:col-span-2 space-y-6">
          
          <div className="p-6 rounded-2xl bg-[#0b2034] border border-slate-800 space-y-6">
            <h3 className="font-bold font-serif text-white text-base flex items-center space-x-2">
              <Coins className="w-5 h-5 text-[#07e3f8]" />
              <span>Sui Token Parameters</span>
            </h3>

            {/* Network Selector */}
            <div className="flex space-x-3 font-serif">
              <button
                type="button"
                onClick={() => setNetwork('testnet')}
                className={`flex-1 py-2.5 rounded-xl text-xs font-semibold border transition-all ${
                  network === 'testnet'
                    ? 'bg-gradient-to-r from-[#07e3f8] to-[#07E3F8] text-[#040916] border-transparent font-bold'
                    : 'bg-slate-950 border-slate-800 text-slate-400'
                }`}
              >
                Sui Testnet (FREE)
              </button>
              <button
                type="button"
                onClick={() => setNetwork('mainnet')}
                className={`flex-1 py-2.5 rounded-xl text-xs font-semibold border transition-all ${
                  network === 'mainnet'
                    ? 'bg-gradient-to-r from-[#07e3f8] to-[#07E3F8] text-[#040916] border-transparent font-bold'
                    : 'bg-slate-950 border-slate-800 text-slate-400'
                }`}
              >
                Sui Mainnet (Low Fee)
              </button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div>
                <label className="block text-xs font-serif font-semibold text-slate-300 mb-1">Token Name</label>
                <input
                  type="text"
                  value={tokenName}
                  onChange={(e) => setTokenName(e.target.value)}
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-white text-xs focus:border-cyan-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-serif font-semibold text-slate-300 mb-1">Token Symbol</label>
                <input
                  type="text"
                  value={symbol}
                  onChange={(e) => setSymbol(e.target.value.toUpperCase())}
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-white text-xs font-mono focus:border-cyan-500 focus:outline-none uppercase"
                />
              </div>

              <div>
                <label className="block text-xs font-serif font-semibold text-slate-300 mb-1">Total Supply</label>
                <input
                  type="number"
                  value={supply}
                  onChange={(e) => setSupply(e.target.value)}
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-white text-xs font-mono focus:border-cyan-500 focus:outline-none"
                />
              </div>

              <div>
                <label className="block text-xs font-serif font-semibold text-slate-300 mb-1">Decimals</label>
                <input
                  type="number"
                  value={decimals}
                  onChange={(e) => setDecimals(Number(e.target.value))}
                  className="w-full px-4 py-2.5 rounded-xl bg-slate-950 border border-slate-800 text-white text-xs font-mono focus:border-cyan-500 focus:outline-none"
                />
                <span className="text-[11px] text-slate-500 font-serif">Standard for Sui tokens is 9</span>
              </div>

              <div className="sm:col-span-2">
                <label className="block text-xs font-serif font-semibold text-slate-300 mb-1">Logo URL / IPFS Link</label>
                <input
                  type="text"
                  value={logoUrl}
                  onChange={(e) => setLogoUrl(e.target.value)}
                  className="w-full px-4 py-2 rounded-xl bg-slate-950 border border-slate-800 text-white text-xs focus:border-cyan-500 focus:outline-none"
                />
              </div>
            </div>

            {/* Immutability & Fixed Supply */}
            <div
              onClick={() => setFixedSupply(!fixedSupply)}
              className={`p-4 rounded-xl border cursor-pointer transition-all flex items-center justify-between ${
                fixedSupply ? 'bg-cyan-950/20 border-cyan-500/40' : 'bg-slate-950 border-slate-800'
              }`}
            >
              <div>
                <div className="text-xs font-bold font-serif text-white flex items-center space-x-1.5">
                  <ShieldCheck className="w-4 h-4 text-emerald-400" />
                  <span>Freeze TreasuryCap (Fixed Supply Guarantee)</span>
                </div>
                <p className="text-[11px] font-serif text-slate-400 mt-0.5">
                  Permanently destroys mint rights by freezing the TreasuryCap object. Essential for community DEX trust on Cetus & Turbos.
                </p>
              </div>
              <div className={`w-5 h-5 rounded flex items-center justify-center border ${fixedSupply ? 'bg-[#07e3f8] border-[#07E3F8] text-[#040916] font-bold' : 'border-slate-700'}`}>
                {fixedSupply && <Check className="w-3.5 h-3.5" />}
              </div>
            </div>
          </div>

          {/* Generated Sui Move Code */}
          <div className="p-6 rounded-2xl bg-[#0b2034] border border-slate-800 space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="font-bold font-serif text-white text-xs flex items-center space-x-2">
                <FileCode className="w-4 h-4 text-[#07e3f8]" />
                <span>Generated Sui Move Package Source</span>
              </h3>
              <button
                onClick={() => copyToClipboard(generatedMoveCode, 'Sui Move Code')}
                className="text-xs text-[#07e3f8] hover:text-[#07E3F8] font-serif font-semibold inline-flex items-center space-x-1"
              >
                <Copy className="w-3.5 h-3.5" />
                <span>Copy Move Code</span>
              </button>
            </div>
            <pre className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-[11px] text-cyan-300 font-mono overflow-x-auto max-h-72">
              {generatedMoveCode}
            </pre>
          </div>

        </div>

        {/* Right Col: Summary */}
        <div className="space-y-6">
          <div className="p-6 rounded-2xl bg-[#0b2034] border border-slate-800 space-y-6 sticky top-28">
            <h3 className="font-bold font-serif text-white text-base flex items-center space-x-2">
              <Rocket className="w-5 h-5 text-[#07e3f8]" />
              <span>Sui Deployment Summary</span>
            </h3>

            <div className="p-4 rounded-xl bg-slate-950 border border-slate-800 space-y-2.5 text-xs font-serif">
              <div className="flex justify-between text-slate-400">
                <span>Network:</span>
                <span className="font-semibold text-[#07e3f8] uppercase">{network}</span>
              </div>
              <div className="flex justify-between text-slate-400">
                <span>Total Supply:</span>
                <span className="font-mono text-white">{Number(supply).toLocaleString()} {symbol}</span>
              </div>
              <div className="flex justify-between text-slate-400">
                <span>Decimals:</span>
                <span className="font-mono text-white">{decimals}</span>
              </div>
              <div className="flex justify-between text-slate-400">
                <span>Cetus DEX Ready:</span>
                <span className="text-emerald-400 font-bold">YES</span>
              </div>
            </div>

            <button
              onClick={handleDeploySui}
              disabled={deploying}
              className="btn-primary w-full py-3.5 px-4 rounded-xl text-xs font-bold transition-all flex items-center justify-center space-x-2 shadow-lg shadow-[#07e3f8]/20"
            >
              <Rocket className="w-4 h-4" />
              <span>{deploying ? 'Publishing Package...' : `Deploy on Sui ${network}`}</span>
            </button>

            {deployedSui && (
              <div className="p-4 rounded-xl bg-slate-950 border border-cyan-500/30 space-y-2 text-xs font-serif">
                <div className="text-emerald-400 font-bold flex items-center space-x-1.5">
                  <CheckCircle2 className="w-4 h-4" />
                  <span>Sui Coin Published!</span>
                </div>
                <div className="text-slate-400 text-[11px]">
                  Package ID:
                  <div className="font-mono text-white break-all">{deployedSui.packageId}</div>
                </div>
                <a
                  href={`https://suiscan.xyz/${network}/object/${deployedSui.packageId}`}
                  target="_blank"
                  rel="noreferrer"
                  className="text-[#07e3f8] underline inline-flex items-center space-x-1 text-[11px]"
                >
                  <span>View on SuiScan Explorer</span>
                  <ExternalLink className="w-3 h-3" />
                </a>
              </div>
            )}
          </div>
        </div>

      </div>

    </div>
  );
}
